export COCOSTUFF_TRAINSET_DIR=/home/liuxiao/cocostuff/dataset/images/train2017
export COCOSTUFF_VALSET_DIR=/home/liuxiao/cocostuff/dataset/images/val2017
export COCOSTUFF_VH_ANNO_DIR=/home/liuxiao/cocostuff/dataset/annotations_pigs_fly/COCOstuff/annotations_virtualhome_compatible
# patchsize 8, 14, 28, 56, 112
# nohup python eval_linear_vh.py --batch_size_per_gpu 256 --anno_dir $COCOSTUFF_VH_ANNO_DIR --img_train_dir $COCOSTUFF_TRAINSET_DIR --img_val_dir $COCOSTUFF_VALSET_DIR --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar --lr 0.1 --num_labels 15  --method 'ours' --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > eval_logs/vicreg_augmem_newarch/r50_b256_eps500_augmem_context/linear_lr1e-1_nonsharing_K200_mdim512_ss_vh.log 2>&1 &
# nohup python object_priming.py --data_path analysis/image_examples/kitchen1.jpeg --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 8 --method 'ours' --output_dir 'object_priming/test'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/test.log 2>&1 &
# nohup python object_priming.py --data_path analysis/image_examples/kitchen1.jpeg --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim2048/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim2048/checkpoint_best.pth.tar  --num_labels 15 --patch_size 28 --method 'ours' --output_dir 'object_priming/test'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/test.log 2>&1 &
# ours
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 8 --method 'ours' --output_dir 'object_priming/ours/patchsize8'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/ours_ps8.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 14 --method 'ours' --output_dir 'object_priming/ours/patchsize14'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/ours_ps14.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 28 --method 'ours' --output_dir 'object_priming/ours/patchsize28'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/ours_ps28.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 56 --method 'ours' --output_dir 'object_priming/ours/patchsize56'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/ours_ps56.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 112 --method 'ours' --output_dir 'object_priming/ours/patchsize112'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/ours_ps112.log 2>&1 &

# ours 2
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search_2/checkpoint_best.pth.tar  --num_labels 15 --patch_size 8 --method 'ours' --output_dir 'object_priming/ours_2/patchsize8'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/ours_ps8_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search_2/checkpoint_best.pth.tar  --num_labels 15 --patch_size 14 --method 'ours' --output_dir 'object_priming/ours_2/patchsize14'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/ours_ps14_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search_2/checkpoint_best.pth.tar  --num_labels 15 --patch_size 28 --method 'ours' --output_dir 'object_priming/ours_2/patchsize28'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/ours_ps28_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search_2/checkpoint_best.pth.tar  --num_labels 15 --patch_size 56 --method 'ours' --output_dir 'object_priming/ours_2/patchsize56'  --dist_url 'tcp://localhost:10014' --gpu 3 --drop_threshold 1.0 > object_priming_logs/ours_ps56_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search_2/checkpoint_best.pth.tar  --num_labels 15 --patch_size 112 --method 'ours' --output_dir 'object_priming/ours_2/patchsize112'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/ours_ps112_2.log 2>&1 &


# simsiam
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 56 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize56'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps56.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 8 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize8'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps8.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 14 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize14'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps14.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 28 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize28'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps28.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 112 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize112'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_p112.log 2>&1 &


# simsiam 1
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_2/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 56 --method 'simsiam' --output_dir 'object_priming/simsiam_1/patchsize56'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps56_1.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_2/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 8 --method 'simsiam' --output_dir 'object_priming/simsiam_1/patchsize8'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps8_1.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_2/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 14 --method 'simsiam' --output_dir 'object_priming/simsiam_1/patchsize14'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps14_1.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_2/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 28 --method 'simsiam' --output_dir 'object_priming/simsiam_1/patchsize28'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps28_1.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_2/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 112 --method 'simsiam' --output_dir 'object_priming/simsiam_1/patchsize112'  --dist_url 'tcp://localhost:10005' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_p112_1.log 2>&1 &

# simsiam 2
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_3/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 56 --method 'simsiam' --output_dir 'object_priming/simsiam_2/patchsize56'  --dist_url 'tcp://localhost:10014' --gpu 1 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps56_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_3/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 8 --method 'simsiam' --output_dir 'object_priming/simsiam_2/patchsize8'  --dist_url 'tcp://localhost:10011' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps8_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_3/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 14 --method 'simsiam' --output_dir 'object_priming/simsiam_2/patchsize14'  --dist_url 'tcp://localhost:10012' --gpu 2 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps14_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_3/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 28 --method 'simsiam' --output_dir 'object_priming/simsiam_2/patchsize28'  --dist_url 'tcp://localhost:10013' --gpu 2 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps28_2.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased_3/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 112 --method 'simsiam' --output_dir 'object_priming/simsiam_2/patchsize112'  --dist_url 'tcp://localhost:10015' --gpu 0 --drop_threshold 1.0 > object_priming_logs/siamsiam_p112_2.log 2>&1 &


# un-standardized
# ours
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 8 --method 'ours' --output_dir 'object_priming/ours/patchsize8_unstandardized'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/ours_ps8_unstandardized.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 14 --method 'ours' --output_dir 'object_priming/ours/patchsize14_unstandardized'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/ours_ps14_unstandardized.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 28 --method 'ours' --output_dir 'object_priming/ours/patchsize28_unstandardized'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/ours_ps28_unstandardized.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 56 --method 'ours' --output_dir 'object_priming/ours/patchsize56_unstandardized_new'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/ours_ps56_unstandardized_new.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 112 --method 'ours' --output_dir 'object_priming/ours/patchsize112_unstandardized'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/ours_ps112_unstandardized.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 28 --method 'ours' --output_dir 'object_priming/ours/patchsize28_unstandardized_new'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/ours_ps28_unstandardized_new.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights unsupervised/vicreg_augmem/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim512_selective_search/checkpoint_0499.pth.tar --linear_weights eval_checkpoints/vicreg_augmem_newarch/augmem_context/linear_lr1e-1_r50_b256_nonsharing_K200_mdim512_selective_search/checkpoint_best.pth.tar  --num_labels 15 --patch_size 14 --method 'ours' --output_dir 'object_priming/ours/patchsize14_unstandardized_new'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/ours_ps14_unstandardized_new.log 2>&1 &

# simsiam
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 56 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize56_unstandardized_new'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps56_unstandardized_new.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 8 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize8_unstandardized'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps8_unstandardized.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 14 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize14_unstandardized'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps14_unstandardized.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 28 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize28_unstandardized'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps28_unstandardized.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 112 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize112_unstandardized'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_p112_unstandardized.log 2>&1 &

# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 28 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize28_unstandardized_new'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps28_unstandardized_new.log 2>&1 &
# nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights 'unsupervised/simsiam/checkpoints_lr1e-2_baseline_imgbased/checkpoint_0599.pth.tar' --linear_weights 'eval_checkpoints/simsiam_baseline/context_linear_lr20_r50_b256_imgbased/checkpoint_best.pth.tar'  --num_labels 15 --patch_size 14 --method 'simsiam' --output_dir 'object_priming/simsiam/patchsize14_unstandardized_new'  --dist_url 'tcp://localhost:10004' --gpu 3 --drop_threshold 1.0 > object_priming_logs/siamsiam_ps14_unstandardized_new.log 2>&1 &

#seco large
nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights /home/liuxiao/ContextReasoning/unsupervised/seco/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lr1e-1_cropscale0.08_1.0/checkpoint_0499.pth.tar --linear_weights  /home/liuxiao/ContextReasoning/eval_checkpoints/vicreg_augmem_newarch/augmem_context/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lre-1_cropscale0.8_1.0/checkpoint_best.pth.tar --num_labels 15 --patch_size 8 --method 'ours' --output_dir 'object_priming/ours_large/patchsize8'  --dist_url 'tcp://localhost:10001' --gpu 0 --drop_threshold 1.0 > object_priming_logs/ours_large_ps8.log 2>&1 &
nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights /home/liuxiao/ContextReasoning/unsupervised/seco/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lr1e-1_cropscale0.08_1.0/checkpoint_0499.pth.tar --linear_weights  /home/liuxiao/ContextReasoning/eval_checkpoints/vicreg_augmem_newarch/augmem_context/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lre-1_cropscale0.8_1.0/checkpoint_best.pth.tar --num_labels 15 --patch_size 14 --method 'ours' --output_dir 'object_priming/ours_large/patchsize14'  --dist_url 'tcp://localhost:10002' --gpu 1 --drop_threshold 1.0 > object_priming_logs/ours_large_ps14.log 2>&1 &
nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights /home/liuxiao/ContextReasoning/unsupervised/seco/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lr1e-1_cropscale0.08_1.0/checkpoint_0499.pth.tar --linear_weights  /home/liuxiao/ContextReasoning/eval_checkpoints/vicreg_augmem_newarch/augmem_context/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lre-1_cropscale0.8_1.0/checkpoint_best.pth.tar --num_labels 15 --patch_size 28 --method 'ours' --output_dir 'object_priming/ours_large/patchsize28'  --dist_url 'tcp://localhost:10003' --gpu 2 --drop_threshold 1.0 > object_priming_logs/ours_large_ps28log 2>&1 &
nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights /home/liuxiao/ContextReasoning/unsupervised/seco/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lr1e-1_cropscale0.08_1.0/checkpoint_0499.pth.tar --linear_weights  /home/liuxiao/ContextReasoning/eval_checkpoints/vicreg_augmem_newarch/augmem_context/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lre-1_cropscale0.8_1.0/checkpoint_best.pth.tar --num_labels 15 --patch_size 56 --method 'ours' --output_dir 'object_priming/ours_large/patchsize56'  --dist_url 'tcp://localhost:10004' --gpu 1 --drop_threshold 1.0 > object_priming_logs/ours_large_ps56.log 2>&1 &
nohup python object_priming.py --data_path ../object_priming/imgset_atleast_3 --arch resnet50 --pretrained_weights /home/liuxiao/ContextReasoning/unsupervised/seco/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lr1e-1_cropscale0.08_1.0/checkpoint_0499.pth.tar --linear_weights  /home/liuxiao/ContextReasoning/eval_checkpoints/vicreg_augmem_newarch/augmem_context/checkpoints_b256_eps500_newarch_nonsharing_context_K200_mdim8192_lre-1_cropscale0.8_1.0/checkpoint_best.pth.tar --num_labels 15 --patch_size 112 --method 'ours' --output_dir 'object_priming/ours_large/patchsize112'  --dist_url 'tcp://localhost:10005' --gpu 2 --drop_threshold 1.0 > object_priming_logs/ours_large_ps112.log 2>&1 &
